module.exports = [
  // ENDLESS FORMS MOST BEAUTIFUL
  // Shudder Before the Beautiful
  'The deepest solace lies in understanding. This ancient unseen stream, a shudder before the beautiful.',
  'Awake, oceanborn!',
  'Behold this force!',
  'Bring the outside in -- explode the self to epiphany.',
  'The very core of life, the soaring high of truth and light.',
  'The music of this awe -- deep silence between the notes -- deafens me with endless love.',
  'This vagrant Island Earth, a pilgrim shining bright, we are shuddering before the beautiful, before the plentiful -- we, the voyagers.',
  'Tales from the seas, cathedral of green.',
  'The unknown, the grand show, the choir of the stars.',
  'Interstellar theatre play, the nebulae curtain falls.',
  'Imagination, evolution, a species from the vale walks in wonder in search of the source of the tale.',
  // Weak Fantasy
  `These stories given to us all are filled with sacrifice and robes of lust.`,
  `Dissonant choirs and downcast eyes, selfhood of a condescending ape.`,
  `Behold the crown of a heavenly spy, forged in blood of those who defy!`,
  `Kiss the ring, praise and sing: he loves you dwelling in fear and sin.`,
  `Fear is a choice you embrace.`,
  `Your only truth: tribal poetry, witchcraft filling your void, lust for fantasy, male necrocracy -- every child worthy of a better tale.`,
  `Pick your author from à la carte fantasy, filled with suffering and slavery.`,
  `You live only for the days to come, shoveling trash of the upper caste.`,
  `Smiling mouth in a rotting head, sucking dry the teat of the scared.`,
  `A storytelling breed we are -- a starving crew with show-off toys.`,
  `From words into war of the worlds, this one we forsake with scorn from lies the strength of our love: mother’s milk, laced with poison for this newborn.`,
  `Wake up child, I have a story to tell: "Once upon a time..."`,
  // Élan
  `Leave the sleep and let the springtime talk in tongues from the time before man.`,
  `Listen to a daffodil tell her tale.`,
  `Let the guest in, walk out, be the first to greet the morn.`,
  `The meadows of heaven await harvest.`,
  `The cliffs unjumped, cold waters untouched, the elsewhere creatures yet unseen.`,
  `Finally your number came up, free fall awaits the brave!`,
  `Come, taste the wine, race the blind -- they will guide you from the light.`,
  `Writing noughts till the end of time...`,
  `Come, surf the clouds, race the dark -- it feeds from the runs undone.`,
  `Meet me where the cliff greets the sea.`,
  `The answer to the riddle before your eyes is in dead leaves and fleeting skies, returning swans and sedulous mice`,
  `Writings on the gardens book, in the minute of a lover’s look.`,
  `Building a sandcastle close to the shore -- a house of cards from a worn out deck.`,
  `A home from the fellowship, poise and calm.`,
  `Write a lyric for the song only you can understand.`,
  `Riding hard every shooting star come to life, open mind, have a laugh at the orthodox.`,
  `Come, drink deep, let the dam of mind seep.`,
  `Travel with great élan; dance a jig at the funeral.`,
  `Come!`,
  // Yours Is an Empty Hope
  `Tear me to bits, enjoy the scene of screen name verbal vanity.`,
  `Churning the words imbued in filth, your tongue oily water under my bridge.`,
  `You have the world, it’s all for you.`,
  `I wish you’d find the lost in you -- grateful for the pain, it proves we’re alive.`,
  `Can you feel it?`,
  `I can’t make you want the truth -- it’s up to you.`,
  `Yours is an empty hope.`,
  `Feed me to pigs in your fantasies.`,
  `Your sea roars bitter elegies, like Narcissus who bribes the pool.`,
  `A hollow voice, ruin with a roof.`,
  `Stop!`,
  `Life is now, still all for you.`,
  `Turn from the hate; turn from the smoke.`,
  `I see the parchment of your soul, the notes, the song.`,
  `Join your voice!`,
  `I can let you have the world; it’s all for you.`,
  // Our Decades in the Sun
  `I climbed off your back not so long ago, to a blooming meadow to a path you’d made for the lightest feet.`,
  `Mother, I am always close to you.`,
  `I will be waving every time you leave.`,
  `Oh, I am you -- the care, the love, the memories.`,
  `We are the story of one.`,
  `Father, I am always close to you.`,
  `You are forever in me.`,
  `This verse we wrote on a road home, for you.`,
  `All this for you!`,
  `Our walk has been sublime -- a soaring ride and gentle lead.`,
  `You have the heart of a true friend.`,
  `One day we’ll meet on that shore again.`,
  // My Walden
  //`Sain y niwl,
  //`Gaunt y goydwig fwsog,
  //`Gwenithfaen, cen y coed, a'r lleuad,
  //`Un gway f'adenydd I dapestri bywyd
  `Light shines bright beyond all the cities of gold, on a road of birdsong and chocolate shops.`,
  `Of buskers, jugglers, innkeeper’s welcoming call the sound of mist, smell of moss-grown woods.`,
  `Weaving my wings from many-colored yarns flying higher, higher, higher into the wild.`,
  `Weaving my world into tapestry of life, its fire golden in my Walden.`,
  `I will taste the manna in every tree, liquid honey and wine from the distant hills`,
  `An early morning greenwood concerto greets my Walden with its eternal voice.`,
  `I do not wish to evade the world, yet I will forever build my own.`,
  `Forever, my home.`,
  // Endless Forms Most Beautiful
  `Come on, hop on, let’s take a ride.`,
  `Come and meet the travelers who came to town.`,
  `They have a tale from the past to tell from the great dark between the stars.`,
  `We are a special speck of dust -- a fleeting moment on an ark.`,
  `A celebration, a resthaven of life!`,
  `Lay on a field of green with mother Eve, with father pine reaching high.`,
  `Look at yourself in the eyes of aye-aye.`,
  `Unfolding rendezvous!`,
  `Deep into the past, follow the aeon path.`,
  `Greet a blade of grass, every endless form most beautiful.`,
  `Alive, aware, in awe before the grandeur of it all.`,
  `Our floating pale blue ark of endless forms most beautiful!`,
  `Beyond aeons we take a ride, welcoming the shrew that survived to see the Tiktaalik take her first walk.`,
  `Witness the birth of flight.`,
  `Deeper down in Panthalassa, a eukaryote finds her way.`,
  `We return to the very first one.`,
  `Greet the one we’ll soon become.`,
  // Edema Ruh
  `One by one, we light the candles of this show.`,
  `One by one, enter the theatre of the primal birth.`,
  `Silently watch the planetary curtain go down.`,
  `Laugh and rejoice as the powerful play greets you tonight.`,
  `We are the Edema Ruh.`,
  `We know the songs the sirens sang.`,
  `See us dream every tale true.`,
  `The verse we leave with you will take you home.`,
  `We’ll give you a key to open all of the gates.`,
  `We’ll show you a sea of starlight to drown all your cares.`,
  `Mirrorhouses, the sweetest kisses and wines, a Debussy dialogue between wind and the roaring sea.`,
  `Dance to the whistle, to the play, to the story, io infinite encores.`,
  `Laugh at the royalty with sad crowns and repeat the chorus once more`,
  // Alpenglow
  `Once upon a time, a song was heard giving birth to a child of earth and verse.`,
  `Together we slay another fright.`,
  `Every Jubjub bird spooks of the past.`,
  `Close your eyes and take a peek.`,
  `The truth is easy to see.`,
  `We were here, roaming on the endless prairie, writing an endless story.`,
  `Building a Walden of our own, we were here.`,
  `Grieving the saddened faces, conquering the darkest places.`,
  `Time to rest now and to finish the show, and become the Music, one with alpenglow.`,
  `Hand in hand, guiding me into light: you, the fairytale guise in blue and white.`,
  `You are my path, my home my star.`,
  `A beautiful tale within the tale, and when the dust needs to move on I will tuck us in on a bed of snow.`,
  `Painting white, silencing the valley we built, together we’ll sleep, devoured by life`,
  // The Greatest Show on Earth
  `Archaean horizon, the first sunrise on a pristine Gaea.`,
  `Opus perfectum somewhere there; us sleeping.`,
  `The cosmic law of gravity pulled the newborns around a fire.`,
  `A careless, cold infinity in every vast direction.`,
  `Lonely farer in the Goldilocks zone, she has a tale to tell.`,
  `From the stellar nursery into a carbon feast.`,
  `Enter LUCA!`,
  `The tapestry of chemistry!`,
  `There’s a writing in the garden leading us to the Mother of all.`,
  `We are one!`,
  `We are a universe!`,
  `Forbears of what will be scions of the Devonian sea.`,
  `Aeons pass, writing the tale of us all, a day-to-day new opening for the greatest show on Earth.`,
  `Ion channels welcoming the outside world to the stuff of stars.`,
  `Bedding the tree of a biological holy.`,
  `Enter, life!`,
  `We are here to care for the garden.`,
  `The wonder of birth of every form most beautiful.`,
  `After a billion years, the show is still here.`,
  `Not a single one of your fathers died young.`,
  `The handy travelers out of Africa.`,
  `Little Lucy of the afar gave birth to fantasy, to idolatry, to self-destructive weaponry.`,
  `Enter the god of gaps, deep within the past atavistic dread of the hunted.`,
  `Enter Ionia, the cradle of thought, the architecture of understanding.`,
  `The human lust to feel so exceptional to rule the Earth.`,
  `Hunger for shiny rocks, for giant mushroom clouds, the will to do just as you’d be done by.`,
  `Enter history, the grand finale.`,
  `Enter Ratkind!`,
  `Man, he took his time in the sun, had a dream to understand a single grain of sand.`,
  `He gave birth to poetry, but one day’ll cease to be.`,
  `Greet the last light of the library!`,
  `We were here!`,
];
